export const DEPOSIT_CC = {
    DEPOSIT_OK: 0x00,
    TOO_MUCH_DEPOSIT: 0x01,
    GAME_CLOSED: 0x02,
    DEPOSIT_FAIL : 0xFF
};

export const TRANSACTION_TYPE = {
    BUY_TICKET: 'BUY_TICKET',
    WINNING: 'WINNING',
    DEPOSIT: 'DEPOSIT',
    DEPOSIT_FEE: 'DEPOSIT_FEE',
    WITHDRAW: 'WITHDRAW',
}
